name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-check:
    name: Code Quality & Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Check TypeScript types
      run: npm run type-check

    - name: Check code formatting
      run: npm run format:check

    - name: Build Vite app
      run: npm run build:vite

    - name: Build Electron app
      run: npm run build:electron

    - name: Security audit
      run: npm audit --audit-level=high
      continue-on-error: true